### PR TITLE
Adds fix to spec file from issue 2121

### PR DESCRIPTION
**Pull request by bmbouter**
https://pulp.plan.io/issues/2121

This will be merged to all other branches. It mimics the fix
in this commit:

https://github.com/pulp/pulp/commit/3f7195f9b4a5e49fafb888575753d58a02a8de47

### CODE REVIEW

**Comment by jeremycline** [comment]
Do we actually want to require the selinux-policy down to the release number?

**Comment by tehsmyers** [comment]
> Do we actually want to require the selinux-policy down to the release number?

It's a >= requirement, which I think makes this OK. Presumably we won't be developing against a policy newer than what's available to users when building the package, so it seems fine to me.

**Comment by bmbouter** [comment]
It probably doesn't matter since we'll get the latest due to the >=. I do know that if for some reason the user gets an older one they may not be able to install the pulp selinux policy. This has only happened when the build system was misconfigured to use an unreleased version of selinux-policy and pulp did install but silently failed to install the pulp selinux policy. This was originally put in to cause that silent error to be not silent. Then again that is an incorrect build config so perhaps we shouldn't guard against that.

@jeremycline I'm 50/50 on this what do you think?

**Comment by jeremycline** [comment]
If our policy is compatible with selinux-policy >= 3 I think we should leave the requirement as-is and if we introduce a feature that requires something more exacting from the selinux-policy requirement we should bump the version. 

It does mean we have to actually think about the version of selinux we require, but I prefer being explicit about the requirements rather than grabbing whatever version the build host has installed (unless we _need_ that, but it sounds like we don't).

If everyone agrees with that, I think this PR can just delete the original `sed` command, as that variable is unused. Note that the RHEL6 specfile is still nearly identical to the specfile in pulp/pulp so it probably should be left as-is in that branch.

**Comment by bmbouter** [comment]
@jeremycline I agree with you, >= 3 should work so I've adjusted the PR to remove those macros which are unused. @seandst or @jeremycline If this looks good to you add back the LGTM please.

I will touch up the other branches with the similar change. @jeremycline As you mentioned, yes I see that the EL6 one is roughly unchanged. I can make a similar commit against it when I am merging this to remove the unnecessary parts from there as well. Sound good?

**Comment by jeremycline** [comment]
Sounds good to me.

**Pull request merged**
